// SPDX-License-Identifier: Apache-2.0
`include "common_defines.vh"
module el2_soc(input logic clk,rst_n,input logic [7:0] gpio_in,
 output logic [7:0] gpio_out,output logic trace_valid,trace_exception,
 output logic [31:0] trace_pc);
 import el2_pkg::*;
 el2_mem_if mem_if();
 el2_mem_if ic_if();
 logic [31:0] haddr,lsu_haddr;
 logic [1:0] htrans,lsu_htrans;
 logic hwrite,lsu_hwrite,hready,hresp,lsu_hready,lsu_hresp;
 logic [2:0] hsize,lsu_hsize;
 logic [63:0] hrdata,lsu_hwdata,lsu_hrdata;
 ahb_mem #(.INSTRUCTION(1)) u_imem(.clk,.rst_n,.haddr,.htrans,.hwrite,.hsize,
   .hwdata(64'b0),.hrdata,.hready,.hresp,.gpio_in(8'b0),.gpio_out());
 ahb_mem u_dmem(.clk,.rst_n,.haddr(lsu_haddr),.htrans(lsu_htrans),.hwrite(lsu_hwrite),
   .hsize(lsu_hsize),.hwdata(lsu_hwdata),.hrdata(lsu_hrdata),.hready(lsu_hready),
   .hresp(lsu_hresp),.gpio_in,.gpio_out);
 el2_veer_wrapper u_cpu(
 .clk(clk),
 .rst_l(rst_n),
 .dbg_rst_l(rst_n),
 .rst_vec(31'b0),
 .nmi_int('0),
 .nmi_vec(31'b0),
 .jtag_id(31'h1),
 .trace_rv_i_insn_ip(),
 .trace_rv_i_address_ip(trace_pc),
 .trace_rv_i_valid_ip(trace_valid),
 .trace_rv_i_exception_ip(trace_exception),
 .trace_rv_i_ecause_ip(),
 .trace_rv_i_interrupt_ip(),
 .trace_rv_i_tval_ip(),
 .haddr(haddr),
 .hburst(),
 .hmastlock(),
 .hprot(),
 .hsize(hsize),
 .htrans(htrans),
 .hwrite(hwrite),
 .hrdata(hrdata),
 .hready(hready),
 .hresp(hresp),
 .lsu_haddr(lsu_haddr),
 .lsu_hburst(),
 .lsu_hmastlock(),
 .lsu_hprot(),
 .lsu_hsize(lsu_hsize),
 .lsu_htrans(lsu_htrans),
 .lsu_hwrite(lsu_hwrite),
 .lsu_hwdata(lsu_hwdata),
 .lsu_hrdata(lsu_hrdata),
 .lsu_hready(lsu_hready),
 .lsu_hresp(lsu_hresp),
 .sb_haddr(),
 .sb_hburst(),
 .sb_hmastlock(),
 .sb_hprot(),
 .sb_hsize(),
 .sb_htrans(),
 .sb_hwrite(),
 .sb_hwdata(),
 .sb_hrdata('0),
 .sb_hready(1'b1),
 .sb_hresp('0),
 .dma_hsel('0),
 .dma_haddr('0),
 .dma_hburst('0),
 .dma_hmastlock('0),
 .dma_hprot('0),
 .dma_hsize('0),
 .dma_htrans('0),
 .dma_hwrite('0),
 .dma_hwdata('0),
 .dma_hreadyin(1'b1),
 .dma_hrdata(),
 .dma_hreadyout(),
 .dma_hresp(),
 .lsu_bus_clk_en(1'b1),
 .ifu_bus_clk_en(1'b1),
 .dbg_bus_clk_en(1'b1),
 .dma_bus_clk_en(1'b1),
 .iccm_ecc_single_error(),
 .iccm_ecc_double_error(),
 .dccm_ecc_single_error(),
 .dccm_ecc_double_error(),
 .dccm_write_readback_error(),
 .timer_int('0),
 .soft_int('0),
 .extintsrc_req('0),
 .dec_tlu_perfcnt0(),
 .dec_tlu_perfcnt1(),
 .dec_tlu_perfcnt2(),
 .dec_tlu_perfcnt3(),
 .jtag_tck('0),
 .jtag_tms(1'b1),
 .jtag_tdi('0),
 .jtag_trst_n(1'b0),
 .jtag_tdo(),
 .jtag_tdoEn(),
 .core_id('0),
 .mpc_debug_halt_req('0),
 .mpc_debug_run_req('0),
 .mpc_reset_run_req(1'b1),
 .mpc_debug_halt_ack(),
 .mpc_debug_run_ack(),
 .debug_brkpt_status(),
 .i_cpu_halt_req('0),
 .o_cpu_halt_ack(),
 .o_cpu_halt_status(),
 .o_debug_mode_status(),
 .i_cpu_run_req('0),
 .o_cpu_run_ack(),
 .scan_mode('0),
 .mbist_mode('0),
 .dmi_core_enable(1'b1),
 .dmi_uncore_enable('0),
 .dmi_uncore_en(),
 .dmi_uncore_wr_en(),
 .dmi_uncore_addr(),
 .dmi_uncore_wdata(),
 .dmi_uncore_rdata('0),
 .dmi_active(),
 .el2_icache_export(ic_if),
 .el2_mem_export(mem_if));
endmodule
